#!/usr/bin/env python3
"""yoshiki build — bake every export format from palette/<slug>/palette.yml.

Source of truth: palette.yml per theme. Variants may declare `inherits: kogane`;
tokens / terminal / base24 are merged over the parent. Run from repo root:

    python3 tools/build.py
"""
import json, sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pacman -S python-yaml")

ROOT = Path(__file__).resolve().parent.parent
PAL = ROOT / "palette"
ORDER = ["kogane", "washi"]


def load(slug: str) -> dict:
    return yaml.safe_load((PAL / slug / "palette.yml").read_text())


def resolve(raw: dict, parent: dict | None) -> dict:
    out = {"meta": raw["meta"], "semantic": raw.get("semantic", {}), "notes": raw.get("notes", {})}
    tokens = dict(parent["tokens"]) if parent else {}
    tokens.update(raw.get("tokens", {}))
    out["tokens"] = tokens

    term = dict(parent["terminal"]) if parent else {}
    t = dict(raw.get("terminal", {}))
    if t.pop("inherit-exact", None) and parent:   # washi: dark island, copy as-is
        out["terminal"] = dict(parent["terminal"])
    else:
        ansi = list(t.pop("ansi", term.get("ansi", [])))
        brights = list(t.pop("brights", term.get("brights", [])))
        if "ansi-black" in t:
            ansi[0] = t.pop("ansi-black")
        if "brights-black" in t:
            brights[0] = t.pop("brights-black")
        term.update(t)
        term["ansi"], term["brights"] = ansi, brights
        out["terminal"] = term

    b24 = dict(parent["base24"]) if parent else {}
    b24.update(raw.get("base24", {}))
    out["base24"] = b24

    roles = dict(parent["roles"]) if parent else {}
    roles.update(raw.get("roles", {}))
    out["roles"] = roles
    return out


def role_value(spec: str, tok: dict):
    """Resolve a role spec ('token' or 'token @NN') to (css_value, base_hex)."""
    name, _, op = spec.partition("@")
    base = tok.get(name.strip(), name.strip())
    if op:
        return f"color-mix(in srgb, {base} {op.strip().rstrip('%')}%, transparent)", base
    return base, base


# WCAG relative luminance / contrast — proof the foundation holds
def _lum(h):
    h = h.lstrip("#")
    c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= .04045 else ((x + .055) / 1.055) ** 2.4 for x in c]
    return .2126 * c[0] + .7152 * c[1] + .0722 * c[2]


def contrast(a, b):
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return round((la + .05) / (lb + .05), 2)


def w(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {path.relative_to(ROOT)}")


def emit(slug: str, p: dict):
    d = PAL / slug
    name, kanji = p["meta"]["name"], p["meta"]["kanji"]
    head = f"yoshiki · {name} {kanji} v{p['meta']['version']} — generated by tools/build.py, edit palette.yml instead"
    tok, term = p["tokens"], p["terminal"]

    # json — resolved machine-readable bundle (tokens + resolved roles)
    roles_for_json = {r: role_value(spec, p["tokens"])[0] for r, spec in p["roles"].items()}
    w(d / f"{slug}.json", json.dumps({**p, "roles_resolved": roles_for_json},
                                      ensure_ascii=False, indent=2) + "\n")

    # roles resolved to css values (the consumer-facing contract)
    roles = {r: role_value(spec, tok)[0] for r, spec in p["roles"].items()}

    # css variables — raw tokens + semantic role aliases (--r-<role>)
    css = [f"/* {head} */", ":root{", "  /* tokens */"]
    css += [f"  --{k}: {v};" for k, v in tok.items()]
    css.append("  /* semantic roles — prefer these */")
    css += [f"  --r-{r.replace('.', '-')}: {v};" for r, v in roles.items()]
    css.append("}")
    w(d / f"{slug}.css", "\n".join(css) + "\n")

    # base24 scheme
    b = {"system": "base24", "name": f"yoshiki {slug}", "author": "Zinzaki",
         "variant": p["meta"]["mode"], "palette": {k: v.lstrip("#") for k, v in sorted(p["base24"].items())}}
    w(d / f"base24-{slug}.yaml", yaml.safe_dump(b, sort_keys=False, allow_unicode=True))

    a, br = term["ansi"], term["brights"]

    # kitty
    k = [f"# {head}",
         f"foreground {term['foreground']}", f"background {term['background']}",
         f"cursor {term['cursor']}", f"selection_background {term['selection_background']}",
         "selection_foreground none"]
    k += [f"color{i} {c}" for i, c in enumerate(a)]
    k += [f"color{i + 8} {c}" for i, c in enumerate(br)]
    w(d / "terminal" / f"kitty-{slug}.conf", "\n".join(k) + "\n")

    # foot
    f = [f"# {head}", "[colors]",
         f"foreground={term['foreground'].lstrip('#')}", f"background={term['background'].lstrip('#')}"]
    f += [f"regular{i}={c.lstrip('#')}" for i, c in enumerate(a)]
    f += [f"bright{i}={c.lstrip('#')}" for i, c in enumerate(br)]
    f += [f"selection-background={term['selection_background'].lstrip('#')}"]
    w(d / "terminal" / f"foot-{slug}.ini", "\n".join(f) + "\n")

    # alacritty
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    al = [f"# {head}", "[colors.primary]",
          f'background = "{term["background"]}"', f'foreground = "{term["foreground"]}"',
          "", "[colors.cursor]", f'cursor = "{term["cursor"]}"', "", "[colors.selection]",
          f'background = "{term["selection_background"]}"', "", "[colors.normal]"]
    al += [f'{n} = "{c}"' for n, c in zip(names, a)]
    al += ["", "[colors.bright]"]
    al += [f'{n} = "{c}"' for n, c in zip(names, br)]
    w(d / "terminal" / f"alacritty-{slug}.toml", "\n".join(al) + "\n")

    # starship palette block
    st = [f"# {head}", f"# usage: palette = \"yoshiki-{slug}\"", f"[palettes.yoshiki-{slug}]"]
    role = {"bg": "ink-0", "surface": "ink-2", "line": "line-0", "border": "line-1",
            "bone": "bone-1", "bonehi": "bone-0", "bonemut": "bone-2", "muted": "bone-3",
            "ghost": "bone-4", "gold": "kin-1", "goldhi": "kin-0", "golddim": "kin-2",
            "scarlet": "aka-1", "scarlethi": "aka-0", "moss": "mori-1", "mosshi": "mori-0",
            "persimmon": "kaki-1", "blue": "hotaru-1", "magenta": "fuji-1", "cyan": "seiji-1"}
    if "lily-1" in tok:
        role.update({"lily": "lily-1", "lilyhi": "lily-0", "petal": "lily-p"})
    st += [f'{k} = "{tok[v]}"' for k, v in role.items() if v in tok]
    w(d / "terminal" / f"starship-{slug}.toml", "\n".join(st) + "\n")


# text roles measured against their real background, with the WCAG floor
CONTRAST_ROWS = [
    ("text.heading", "bg.surface", 4.5), ("text.body", "bg.surface", 4.5),
    ("text.secondary", "bg.surface", 4.5), ("text.muted", "bg.surface", 4.5),
    ("text.ghost", "bg.surface", 3.0), ("text.gold", "bg.surface", 4.5),
    ("action.text", "bg.raised", 4.5), ("ok.text", "ok.wash", 4.5),
    ("warn.text", "bg.surface", 3.0), ("danger.text", "danger.wash", 4.5),
    ("special.text", "bg.surface", 4.5),
]


def write_contrast(resolved: dict):
    head = ["# Contrast — WCAG proof\n",
            "Auto-generated by `tools/build.py`. Every text role is measured against",
            "the background it actually sits on. Decorative gold edges (`border.gold`)",
            "are excluded — an edge needs only 3:1, and gold-as-text uses `text.gold`.\n"]
    lines = []
    ok_all = True
    for p in resolved.values():
        tok = p["tokens"]

        def hexof(role):
            return role_value(p["roles"][role], tok)[1]
        lines.append(f"## {p['meta']['name']} {p['meta']['kanji']} ({p['meta']['mode']})\n")
        lines.append("| role | on | ratio | floor | |")
        lines.append("|---|---|---|---|---|")
        for fg, bg, floor in CONTRAST_ROWS:
            c = contrast(hexof(fg), hexof(bg))
            ok = c >= floor
            ok_all &= ok
            lines.append(f"| `{fg}` | `{bg}` | {c}:1 | {floor} | {'✓' if ok else '✗ FAIL'} |")
        lines.append("")
    head.append(f"**Status: {'all roles pass' if ok_all else 'FAILURES PRESENT'}.**\n")
    w(ROOT / "CONTRAST.md", "\n".join(head + lines))
    return ok_all


def main():
    resolved = {}
    for slug in ORDER:
        raw = load(slug)
        parent = resolved.get(raw.get("inherits", ""))
        resolved[slug] = resolve(raw, parent)
        emit(slug, resolved[slug])
    ok = write_contrast(resolved)
    print("done." if ok else "done — CONTRAST FAILURES, see CONTRAST.md")


if __name__ == "__main__":
    main()
