#!/usr/bin/env python3
"""yoshiki build — bake every export format from palette/<slug>/palette.yml.

Source of truth: palette.yml per theme. Variants may declare `inherits: kogane`;
tokens / terminal / base24 are merged over the parent. Run from repo root:

    python3 tools/build.py
"""
import json, sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pacman -S python-yaml")

ROOT = Path(__file__).resolve().parent.parent
PAL = ROOT / "canon" / "palette"          # definition (source of truth)
LIB = ROOT / "library" / "themes"         # ready-to-use program themes
ORDER = ["kogane", "washi"]


def load(slug: str) -> dict:
    return yaml.safe_load((PAL / slug / "palette.yml").read_text())


def resolve(raw: dict, parent: dict | None) -> dict:
    out = {"meta": raw["meta"], "semantic": raw.get("semantic", {}), "notes": raw.get("notes", {})}
    tokens = dict(parent["tokens"]) if parent else {}
    tokens.update(raw.get("tokens", {}))
    out["tokens"] = tokens

    term = dict(parent["terminal"]) if parent else {}
    t = dict(raw.get("terminal", {}))
    if t.pop("inherit-exact", None) and parent:   # washi: dark island, copy as-is
        out["terminal"] = dict(parent["terminal"])
    else:
        ansi = list(t.pop("ansi", term.get("ansi", [])))
        brights = list(t.pop("brights", term.get("brights", [])))
        if "ansi-black" in t:
            ansi[0] = t.pop("ansi-black")
        if "brights-black" in t:
            brights[0] = t.pop("brights-black")
        term.update(t)
        term["ansi"], term["brights"] = ansi, brights
        out["terminal"] = term

    b24 = dict(parent["base24"]) if parent else {}
    b24.update(raw.get("base24", {}))
    out["base24"] = b24

    roles = dict(parent["roles"]) if parent else {}
    roles.update(raw.get("roles", {}))
    out["roles"] = roles
    return out


def role_value(spec: str, tok: dict):
    """Resolve a role spec ('token' or 'token @NN') to (css_value, base_hex)."""
    name, _, op = spec.partition("@")
    base = tok.get(name.strip(), name.strip())
    if op:
        return f"color-mix(in srgb, {base} {op.strip().rstrip('%')}%, transparent)", base
    return base, base


# WCAG relative luminance / contrast — proof the foundation holds
def _lum(h):
    h = h.lstrip("#")
    c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= .04045 else ((x + .055) / 1.055) ** 2.4 for x in c]
    return .2126 * c[0] + .7152 * c[1] + .0722 * c[2]


def contrast(a, b):
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return round((la + .05) / (lb + .05), 2)


def w(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {path.relative_to(ROOT)}")


def emit(slug: str, p: dict):
    d = PAL / slug
    name, kanji = p["meta"]["name"], p["meta"]["kanji"]
    head = f"yoshiki · {name} {kanji} v{p['meta']['version']} — generated by tools/build.py, edit palette.yml instead"
    tok, term = p["tokens"], p["terminal"]

    # json — resolved machine-readable bundle (tokens + resolved roles)
    roles_for_json = {r: role_value(spec, p["tokens"])[0] for r, spec in p["roles"].items()}
    w(d / f"{slug}.json", json.dumps({**p, "roles_resolved": roles_for_json},
                                      ensure_ascii=False, indent=2) + "\n")

    # roles resolved to css values (the consumer-facing contract)
    roles = {r: role_value(spec, tok)[0] for r, spec in p["roles"].items()}

    # css variables — raw tokens + semantic role aliases (--r-<role>)
    css = [f"/* {head} */", ":root{", "  /* tokens */"]
    css += [f"  --{k}: {v};" for k, v in tok.items()]
    css.append("  /* semantic roles — prefer these */")
    css += [f"  --r-{r.replace('.', '-')}: {v};" for r, v in roles.items()]
    css.append("}")
    w(d / f"{slug}.css", "\n".join(css) + "\n")

    # ── ready-to-use program themes → library/themes/<app>/<slug>.<ext> ──
    # base24 scheme (base16/base24 ecosystems)
    b = {"system": "base24", "name": f"yoshiki {slug}", "author": "Zinzaki",
         "variant": p["meta"]["mode"], "palette": {k: v.lstrip("#") for k, v in sorted(p["base24"].items())}}
    w(LIB / "base24" / f"{slug}.yaml", yaml.safe_dump(b, sort_keys=False, allow_unicode=True))

    a, br = term["ansi"], term["brights"]

    # kitty
    k = [f"# {head}",
         f"foreground {term['foreground']}", f"background {term['background']}",
         f"cursor {term['cursor']}", f"selection_background {term['selection_background']}",
         "selection_foreground none"]
    k += [f"color{i} {c}" for i, c in enumerate(a)]
    k += [f"color{i + 8} {c}" for i, c in enumerate(br)]
    w(LIB / "kitty" / f"{slug}.conf", "\n".join(k) + "\n")

    # foot
    f = [f"# {head}", "[colors]",
         f"foreground={term['foreground'].lstrip('#')}", f"background={term['background'].lstrip('#')}"]
    f += [f"regular{i}={c.lstrip('#')}" for i, c in enumerate(a)]
    f += [f"bright{i}={c.lstrip('#')}" for i, c in enumerate(br)]
    f += [f"selection-background={term['selection_background'].lstrip('#')}"]
    w(LIB / "foot" / f"{slug}.ini", "\n".join(f) + "\n")

    # alacritty
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    al = [f"# {head}", "[colors.primary]",
          f'background = "{term["background"]}"', f'foreground = "{term["foreground"]}"',
          "", "[colors.cursor]", f'cursor = "{term["cursor"]}"', "", "[colors.selection]",
          f'background = "{term["selection_background"]}"', "", "[colors.normal]"]
    al += [f'{n} = "{c}"' for n, c in zip(names, a)]
    al += ["", "[colors.bright]"]
    al += [f'{n} = "{c}"' for n, c in zip(names, br)]
    w(LIB / "alacritty" / f"{slug}.toml", "\n".join(al) + "\n")

    # starship palette block
    st = [f"# {head}", f"# usage: palette = \"yoshiki-{slug}\"", f"[palettes.yoshiki-{slug}]"]
    role = {"bg": "ink-0", "surface": "ink-2", "line": "line-0", "border": "line-1",
            "bone": "bone-1", "bonehi": "bone-0", "bonemut": "bone-2", "muted": "bone-3",
            "ghost": "bone-4", "gold": "kin-1", "goldhi": "kin-0", "golddim": "kin-2",
            "scarlet": "aka-1", "scarlethi": "aka-0", "moss": "mori-1", "mosshi": "mori-0",
            "persimmon": "kaki-1", "blue": "hotaru-1", "magenta": "fuji-1", "cyan": "seiji-1"}
    if "lily-1" in tok:
        role.update({"lily": "lily-1", "lilyhi": "lily-0", "petal": "lily-p"})
    st += [f'{k} = "{tok[v]}"' for k, v in role.items() if v in tok]
    w(LIB / "starship" / f"{slug}.toml", "\n".join(st) + "\n")

    # editors render on the theme's own surfaces (light theme = paper)
    light = p["meta"]["mode"] == "light"
    efg = tok["bone-1"]
    ebg = tok["ink-0"]
    sel = "#3F3112" if light else tok.get("kin-w", "#3F3112")

    # vscode — theme.json (workbench essentials + token colors via roles)
    def tc(scopes, color, style=None):
        s = {"scope": scopes, "settings": {"foreground": color}}
        if style:
            s["settings"]["fontStyle"] = style
        return s
    vscode = {
        "name": f"yoshiki {slug}", "type": p["meta"]["mode"],
        "colors": {
            "editor.background": ebg, "editor.foreground": efg,
            "editorCursor.foreground": term["cursor"],
            "editor.selectionBackground": sel,
            "editorLineNumber.foreground": tok["bone-4"],
            "editorLineNumber.activeForeground": tok["kin-1"],
            "sideBar.background": tok["ink-1"], "sideBar.foreground": tok["bone-2"],
            "activityBar.background": tok["ink-1"], "activityBar.foreground": tok["kin-1"],
            "statusBar.background": tok["ink-1"], "statusBar.foreground": tok["bone-3"],
            "titleBar.activeBackground": tok["ink-1"], "titleBar.activeForeground": tok["bone-1"],
            "tab.activeBackground": tok["ink-2"], "tab.activeForeground": tok["bone-0"],
            "tab.inactiveForeground": tok["bone-4"],
            "focusBorder": tok["kin-2"], "panel.border": tok["line-0"],
            "button.background": tok["ink-2"], "button.foreground": tok["kin-1"],
            "errorForeground": tok["aka-0"],
        },
        "tokenColors": [
            tc(["comment"], tok["bone-4"], "italic"),
            tc(["keyword", "storage", "keyword.control"], tok["kin-1"]),
            tc(["string"], tok["mori-0"]),
            tc(["constant.numeric", "constant"], tok["kaki-1"]),
            tc(["entity.name.function", "support.function"], tok["bone-0"]),
            tc(["entity.name.type", "support.type", "entity.name.class"], tok["hotaru-1"]),
            tc(["variable"], tok["bone-1"]),
            tc(["constant.language", "variable.language"], tok["fuji-1"]),
            tc(["invalid", "message.error"], tok["aka-0"]),
        ],
    }
    w(LIB / "vscode" / f"{slug}.json", json.dumps(vscode, ensure_ascii=False, indent=2) + "\n")

    # neovim — lua colorscheme (core + treesitter)
    nv = [f"-- {head}", '-- usage: copy to colors/, then :colorscheme yoshiki-' + slug,
          'vim.cmd("highlight clear")', 'vim.cmd("syntax reset")',
          f'vim.o.background = "{p["meta"]["mode"]}"',
          f'vim.g.colors_name = "yoshiki-{slug}"',
          "local hl = vim.api.nvim_set_hl"]
    hi = [("Normal", efg, ebg), ("Comment", tok["bone-4"], None),
          ("Keyword", tok["kin-1"], None), ("Statement", tok["kin-1"], None),
          ("String", tok["mori-0"], None), ("Number", tok["kaki-1"], None),
          ("Function", tok["bone-0"], None), ("Type", tok["hotaru-1"], None),
          ("Constant", tok["fuji-1"], None), ("Identifier", tok["bone-1"], None),
          ("Error", tok["aka-0"], None), ("LineNr", tok["bone-4"], None),
          ("CursorLineNr", tok["kin-1"], None), ("Visual", None, sel),
          ("Pmenu", tok["bone-2"], tok["ink-2"]), ("PmenuSel", tok["ink-0"], tok["kin-1"])]
    for g, f_, b_ in hi:
        parts = []
        if f_:
            parts.append(f'fg = "{f_}"')
        if b_:
            parts.append(f'bg = "{b_}"')
        if g == "Comment":
            parts.append("italic = true")
        nv.append(f'hl(0, "{g}", {{ {", ".join(parts)} }})')
    nv += [f'hl(0, "@{a}", {{ link = "{b}" }})' for a, b in
           [("keyword", "Keyword"), ("string", "String"), ("number", "Number"),
            ("function", "Function"), ("type", "Type"), ("comment", "Comment"),
            ("constant", "Constant")]]
    w(LIB / "neovim" / f"{slug}.lua", "\n".join(nv) + "\n")

    # tmux — status palette (generated; mirrors the hand config in ../configs/tmux)
    tm = [f"# {head}",
          f'set -g status-style "bg={ebg},fg={tok["bone-3"]}"',
          f'set -g status-left-style "fg={tok["kin-1"]}"',
          f'set -g window-status-current-style "fg={tok["bone-0"]}"',
          f'set -g window-status-style "fg={tok["bone-4"]}"',
          f'set -g status-right-style "fg={tok["kin-2"]}"',
          f'set -g pane-border-style "fg={tok["line-0"]}"',
          f'set -g pane-active-border-style "fg={tok["kin-2"]}"',
          f'set -g mode-style "bg={sel},fg={tok["bone-0"]}"']
    w(LIB / "tmux" / f"{slug}.tmux", "\n".join(tm) + "\n")

    # btop — theme
    def bt(k, c):
        return f'theme[{k}]="{c}"'
    a, br = term["ansi"], term["brights"]
    bp = [f"# {head}",
          bt("main_bg", ebg), bt("main_fg", efg),
          bt("title", tok["bone-0"]), bt("hi_fg", tok["kin-1"]),
          bt("selected_bg", sel), bt("selected_fg", tok["kin-0"]),
          bt("inactive_fg", tok["bone-4"]), bt("graph_text", tok["bone-2"]),
          bt("proc_misc", tok["mori-0"]), bt("cpu_box", tok["line-1"]),
          bt("div_line", tok["line-0"]),
          bt("temp_start", tok["mori-1"]), bt("temp_mid", tok["kaki-1"]), bt("temp_end", tok["aka-1"]),
          bt("cpu_start", tok["mori-1"]), bt("cpu_mid", tok["kin-2"]), bt("cpu_end", tok["kin-0"]),
          bt("free_start", tok["seiji-1"]), bt("free_mid", tok["hotaru-1"]), bt("free_end", tok["fuji-1"])]
    w(LIB / "btop" / f"{slug}.theme", "\n".join(bp) + "\n")


# text roles measured against their real background, with the WCAG floor
CONTRAST_ROWS = [
    ("text.heading", "bg.surface", 4.5), ("text.body", "bg.surface", 4.5),
    ("text.secondary", "bg.surface", 4.5), ("text.muted", "bg.surface", 4.5),
    ("text.ghost", "bg.surface", 3.0), ("text.gold", "bg.surface", 4.5),
    ("action.text", "bg.raised", 4.5), ("ok.text", "ok.wash", 4.5),
    ("warn.text", "bg.surface", 3.0), ("danger.text", "danger.wash", 4.5),
    ("special.text", "bg.surface", 4.5),
]


def write_contrast(resolved: dict):
    head = ["# Contrast — WCAG proof\n",
            "Auto-generated by `tools/build.py`. Every text role is measured against",
            "the background it actually sits on. Decorative gold edges (`border.gold`)",
            "are excluded — an edge needs only 3:1, and gold-as-text uses `text.gold`.\n"]
    lines = []
    ok_all = True
    for p in resolved.values():
        tok = p["tokens"]

        def hexof(role):
            return role_value(p["roles"][role], tok)[1]
        lines.append(f"## {p['meta']['name']} ({p['meta']['mode']})\n")
        lines.append("| role | on | ratio | floor | |")
        lines.append("|---|---|---|---|---|")
        for fg, bg, floor in CONTRAST_ROWS:
            c = contrast(hexof(fg), hexof(bg))
            ok = c >= floor
            ok_all &= ok
            lines.append(f"| `{fg}` | `{bg}` | {c}:1 | {floor} | {'✓' if ok else '✗ FAIL'} |")
        lines.append("")
    head.append(f"**Status: {'all roles pass' if ok_all else 'FAILURES PRESENT'}.**\n")
    w(PAL / "CONTRAST.md", "\n".join(head + lines))
    return ok_all


def main():
    resolved = {}
    for slug in ORDER:
        raw = load(slug)
        parent = resolved.get(raw.get("inherits", ""))
        resolved[slug] = resolve(raw, parent)
        emit(slug, resolved[slug])
    ok = write_contrast(resolved)
    print("done." if ok else "done — CONTRAST FAILURES, see CONTRAST.md")


if __name__ == "__main__":
    main()
