#!/usr/bin/env python3
"""yoshiki build — bake every export format from palette/<slug>/palette.yml.

Source of truth: palette.yml per theme. Variants may declare `inherits: kogane`;
tokens / terminal / base24 are merged over the parent. Run from repo root:

    python3 tools/build.py
"""
import json, sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML required: pacman -S python-yaml")

ROOT = Path(__file__).resolve().parent.parent
PAL = ROOT / "canon" / "palette"          # definition (source of truth)
LIB = ROOT / "library" / "themes"         # ready-to-use program themes
ORDER = ["kogane", "washi"]


def load(slug: str) -> dict:
    return yaml.safe_load((PAL / slug / "palette.yml").read_text())


def resolve(raw: dict, parent: dict | None) -> dict:
    out = {"meta": raw["meta"], "semantic": raw.get("semantic", {}), "notes": raw.get("notes", {})}
    tokens = dict(parent["tokens"]) if parent else {}
    tokens.update(raw.get("tokens", {}))
    out["tokens"] = tokens

    term = dict(parent["terminal"]) if parent else {}
    t = dict(raw.get("terminal", {}))
    if t.pop("inherit-exact", None) and parent:   # washi: dark island, copy as-is
        out["terminal"] = dict(parent["terminal"])
    else:
        ansi = list(t.pop("ansi", term.get("ansi", [])))
        brights = list(t.pop("brights", term.get("brights", [])))
        if "ansi-black" in t:
            ansi[0] = t.pop("ansi-black")
        if "brights-black" in t:
            brights[0] = t.pop("brights-black")
        term.update(t)
        term["ansi"], term["brights"] = ansi, brights
        out["terminal"] = term

    b24 = dict(parent["base24"]) if parent else {}
    b24.update(raw.get("base24", {}))
    out["base24"] = b24

    roles = dict(parent["roles"]) if parent else {}
    roles.update(raw.get("roles", {}))
    out["roles"] = roles
    return out


def role_value(spec: str, tok: dict):
    """Resolve a role spec ('token' or 'token @NN') to (css_value, base_hex)."""
    name, _, op = spec.partition("@")
    base = tok.get(name.strip(), name.strip())
    if op:
        return f"color-mix(in srgb, {base} {op.strip().rstrip('%')}%, transparent)", base
    return base, base


# WCAG relative luminance / contrast — proof the foundation holds
def _lum(h):
    h = h.lstrip("#")
    c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= .04045 else ((x + .055) / 1.055) ** 2.4 for x in c]
    return .2126 * c[0] + .7152 * c[1] + .0722 * c[2]


def contrast(a, b):
    la, lb = sorted((_lum(a), _lum(b)), reverse=True)
    return round((la + .05) / (lb + .05), 2)


def w(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"  {path.relative_to(ROOT)}")


def emit(slug: str, p: dict):
    d = PAL / slug
    name, kanji = p["meta"]["name"], p["meta"]["kanji"]
    head = f"yoshiki · {name} {kanji} v{p['meta']['version']} — generated by tools/build.py, edit palette.yml instead"
    tok, term = p["tokens"], p["terminal"]

    # json — resolved machine-readable bundle (tokens + resolved roles)
    roles_for_json = {r: role_value(spec, p["tokens"])[0] for r, spec in p["roles"].items()}
    w(d / f"{slug}.json", json.dumps({**p, "roles_resolved": roles_for_json},
                                      ensure_ascii=False, indent=2) + "\n")

    # dtcg — W3C Design Tokens (agent / Style-Dictionary readable): tokens grouped by
    # prefix under `color`, roles as aliases under `role` (or a mix value for @NN).
    def dtcg_ref(name):
        g, sep, m = name.partition("-")
        return f"{{color.{g}.{m}}}" if sep else f"{{color.{name}}}"
    color_tree: dict = {}
    for k, v in tok.items():
        g, sep, m = k.partition("-")
        if sep:
            color_tree.setdefault(g, {})[m] = {"$value": v, "$type": "color"}
        else:
            color_tree[k] = {"$value": v, "$type": "color"}
    role_tree = {}
    for r, spec in p["roles"].items():
        nm, _, op = spec.partition("@")
        val = role_value(spec, tok)[0] if op else dtcg_ref(nm.strip())
        role_tree[r.replace(".", "-")] = {"$value": val, "$type": "color"}
    dtcg = {"$description": f"yoshiki {slug} {kanji} — W3C DTCG design tokens (generated)",
            "color": color_tree, "role": role_tree}
    w(d / f"{slug}.tokens.json", json.dumps(dtcg, ensure_ascii=False, indent=2) + "\n")

    # roles resolved to css values (the consumer-facing contract)
    roles = {r: role_value(spec, tok)[0] for r, spec in p["roles"].items()}

    # css variables — raw tokens + semantic role aliases (--r-<role>)
    css = [f"/* {head} */", ":root{", "  /* tokens */"]
    css += [f"  --{k}: {v};" for k, v in tok.items()]
    css.append("  /* semantic roles — prefer these */")
    css += [f"  --r-{r.replace('.', '-')}: {v};" for r, v in roles.items()]
    css.append("}")
    w(d / f"{slug}.css", "\n".join(css) + "\n")

    # ── ready-to-use program themes → library/themes/<app>/<slug>.<ext> ──
    # base24 scheme (base16/base24 ecosystems)
    b = {"system": "base24", "name": f"yoshiki {slug}", "author": "Zinzaki",
         "variant": p["meta"]["mode"], "palette": {k: v.lstrip("#") for k, v in sorted(p["base24"].items())}}
    w(LIB / "base24" / f"{slug}.yaml", yaml.safe_dump(b, sort_keys=False, allow_unicode=True))

    a, br = term["ansi"], term["brights"]

    # kitty
    k = [f"# {head}",
         f"foreground {term['foreground']}", f"background {term['background']}",
         f"cursor {term['cursor']}", f"selection_background {term['selection_background']}",
         "selection_foreground none"]
    k += [f"color{i} {c}" for i, c in enumerate(a)]
    k += [f"color{i + 8} {c}" for i, c in enumerate(br)]
    w(LIB / "kitty" / f"{slug}.conf", "\n".join(k) + "\n")

    # foot
    f = [f"# {head}", "[colors]",
         f"foreground={term['foreground'].lstrip('#')}", f"background={term['background'].lstrip('#')}"]
    f += [f"regular{i}={c.lstrip('#')}" for i, c in enumerate(a)]
    f += [f"bright{i}={c.lstrip('#')}" for i, c in enumerate(br)]
    f += [f"selection-background={term['selection_background'].lstrip('#')}"]
    w(LIB / "foot" / f"{slug}.ini", "\n".join(f) + "\n")

    # alacritty
    names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    al = [f"# {head}", "[colors.primary]",
          f'background = "{term["background"]}"', f'foreground = "{term["foreground"]}"',
          "", "[colors.cursor]", f'cursor = "{term["cursor"]}"', "", "[colors.selection]",
          f'background = "{term["selection_background"]}"', "", "[colors.normal]"]
    al += [f'{n} = "{c}"' for n, c in zip(names, a)]
    al += ["", "[colors.bright]"]
    al += [f'{n} = "{c}"' for n, c in zip(names, br)]
    w(LIB / "alacritty" / f"{slug}.toml", "\n".join(al) + "\n")

    # starship palette block
    st = [f"# {head}", f"# usage: palette = \"yoshiki-{slug}\"", f"[palettes.yoshiki-{slug}]"]
    role = {"bg": "ink-0", "surface": "ink-2", "line": "line-0", "border": "line-1",
            "bone": "bone-1", "bonehi": "bone-0", "bonemut": "bone-2", "muted": "bone-3",
            "ghost": "bone-4", "gold": "kin-1", "goldhi": "kin-0", "golddim": "kin-2",
            "scarlet": "aka-1", "scarlethi": "aka-0", "moss": "mori-1", "mosshi": "mori-0",
            "persimmon": "kaki-1", "blue": "hotaru-1", "magenta": "fuji-1", "cyan": "seiji-1"}
    if "lily-1" in tok:
        role.update({"lily": "lily-1", "lilyhi": "lily-0", "petal": "lily-p"})
    st += [f'{k} = "{tok[v]}"' for k, v in role.items() if v in tok]
    w(LIB / "starship" / f"{slug}.toml", "\n".join(st) + "\n")

    # ── editors render on the theme's own surfaces (light theme = paper),
    #    but the integrated terminal stays a dark island, per the language.
    light = p["meta"]["mode"] == "light"
    efg, ebg = tok["bone-1"], tok["ink-0"]
    sel = "#3F3112" if light else tok.get("kin-w", "#3F3112")
    line_hl = tok["ink-3"] if light else tok["ink-2"]   # current-line wash
    gold_t = roles["text.gold"]      # gold as text (washi sinks it for contrast)
    gold_e = roles["border.gold"]    # gold as edge / underline
    gold_hi, gold_dim = tok["kin-0"], tok["kin-2"]
    sx = lambda r: roles[r]          # a syntax role → its resolved value

    def aa(hexv, alpha):             # 8-digit #rrggbbaa (translucent overlay)
        return hexv[:7] + alpha

    # vscode — full theme.json: workbench, integrated terminal, tokens, semantic
    def tc(scopes, color, style=None):
        st = {"foreground": color}
        if style:
            st["fontStyle"] = style
        return {"scope": scopes, "settings": st}

    nm8 = ["Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "White"]
    ansi_colors = {}
    for i, n in enumerate(nm8):
        ansi_colors[f"terminal.ansi{n}"] = a[i]
        ansi_colors[f"terminal.ansiBright{n}"] = br[i]

    colors = {
        # base
        "foreground": efg, "focusBorder": gold_e, "errorForeground": tok["aka-0"],
        "descriptionForeground": tok["bone-3"], "icon.foreground": tok["bone-3"],
        "selection.background": aa(gold_e, "33"),
        "widget.border": tok["line-0"], "sash.hoverBorder": gold_e,
        "scrollbar.shadow": "#00000000",
        "scrollbarSlider.background": aa(tok["bone-4"], "33"),
        "scrollbarSlider.hoverBackground": aa(tok["bone-4"], "55"),
        "scrollbarSlider.activeBackground": aa(tok["bone-4"], "88"),
        "progressBar.background": gold_e,
        # editor body
        "editor.background": ebg, "editor.foreground": efg,
        "editorCursor.foreground": term["cursor"],
        "editor.selectionBackground": aa(gold_e, "33"),
        "editor.selectionHighlightBackground": aa(gold_e, "22"),
        "editor.wordHighlightBackground": aa(gold_e, "22"),
        "editor.wordHighlightStrongBackground": aa(gold_e, "33"),
        "editor.findMatchBackground": aa(gold_hi, "55"),
        "editor.findMatchHighlightBackground": aa(gold_hi, "30"),
        "editor.lineHighlightBackground": line_hl, "editor.lineHighlightBorder": "#00000000",
        "editorLineNumber.foreground": tok["bone-4"],
        "editorLineNumber.activeForeground": gold_t,
        "editorIndentGuide.background1": tok["line-0"],
        "editorIndentGuide.activeBackground1": tok["line-1"],
        "editorWhitespace.foreground": aa(tok["bone-4"], "55"),
        "editorRuler.foreground": tok["line-0"],
        "editorCodeLens.foreground": tok["bone-4"],
        "editorInlayHint.foreground": tok["bone-4"], "editorInlayHint.background": "#00000000",
        "editorBracketMatch.background": aa(gold_e, "22"), "editorBracketMatch.border": gold_dim,
        "editorBracketHighlight.foreground1": gold_t, "editorBracketHighlight.foreground2": tok["hotaru-1"],
        "editorBracketHighlight.foreground3": tok["mori-0"], "editorBracketHighlight.foreground4": tok["fuji-1"],
        "editorBracketHighlight.foreground5": tok["seiji-1"], "editorBracketHighlight.foreground6": tok["kaki-1"],
        "editorBracketHighlight.unexpectedBracket.foreground": tok["aka-0"],
        "editorGutter.addedBackground": tok["mori-1"], "editorGutter.modifiedBackground": tok["kaki-1"],
        "editorGutter.deletedBackground": tok["aka-1"], "editorGutter.foldingControlForeground": tok["bone-3"],
        "editorError.foreground": tok["aka-0"], "editorWarning.foreground": tok["kaki-1"],
        "editorInfo.foreground": gold_t, "editorHint.foreground": tok["seiji-1"],
        "editorOverviewRuler.border": "#00000000",
        "editorOverviewRuler.findMatchForeground": aa(gold_hi, "99"),
        "editorOverviewRuler.errorForeground": tok["aka-1"],
        "editorOverviewRuler.warningForeground": tok["kaki-1"],
        "editorOverviewRuler.addedForeground": tok["mori-1"],
        "editorOverviewRuler.modifiedForeground": tok["kaki-1"],
        "editorOverviewRuler.deletedForeground": tok["aka-1"],
        # diff
        "diffEditor.insertedTextBackground": aa(tok["mori-1"], "22"),
        "diffEditor.removedTextBackground": aa(tok["aka-1"], "22"),
        "diffEditor.insertedLineBackground": aa(tok["mori-1"], "14"),
        "diffEditor.removedLineBackground": aa(tok["aka-1"], "14"),
        # widgets / suggest / hover / peek
        "editorWidget.background": tok["ink-1"], "editorWidget.border": tok["line-0"],
        "editorWidget.foreground": tok["bone-1"],
        "editorSuggestWidget.background": tok["ink-1"], "editorSuggestWidget.border": tok["line-0"],
        "editorSuggestWidget.foreground": tok["bone-2"], "editorSuggestWidget.selectedBackground": tok["ink-3"],
        "editorSuggestWidget.highlightForeground": gold_t,
        "editorHoverWidget.background": tok["ink-1"], "editorHoverWidget.border": tok["line-0"],
        "peekView.border": gold_dim, "peekViewEditor.background": tok["ink-1"],
        "peekViewResult.background": tok["ink-1"], "peekViewResult.selectionBackground": tok["ink-3"],
        "peekViewTitle.background": tok["ink-2"], "peekViewTitleLabel.foreground": tok["bone-0"],
        "peekViewResult.matchHighlightBackground": aa(gold_hi, "40"),
        "peekViewEditor.matchHighlightBackground": aa(gold_hi, "40"),
        # chrome: tabs / groups / title / status / activity / sidebar
        "editorGroup.border": tok["line-0"],
        "editorGroupHeader.tabsBackground": tok["ink-1"], "editorGroupHeader.noTabsBackground": tok["ink-1"],
        "editorGroupHeader.border": tok["line-0"],
        "tab.activeBackground": ebg, "tab.inactiveBackground": tok["ink-1"],
        "tab.activeForeground": tok["bone-0"], "tab.inactiveForeground": tok["bone-4"],
        "tab.hoverForeground": tok["bone-1"], "tab.border": "#00000000",
        "tab.activeBorderTop": gold_e, "tab.unfocusedActiveForeground": tok["bone-2"],
        "titleBar.activeBackground": tok["ink-1"], "titleBar.activeForeground": tok["bone-1"],
        "titleBar.inactiveBackground": tok["ink-1"], "titleBar.inactiveForeground": tok["bone-4"],
        "titleBar.border": tok["line-0"],
        "statusBar.background": tok["ink-1"], "statusBar.foreground": tok["bone-3"],
        "statusBar.border": tok["line-0"], "statusBar.noFolderBackground": tok["ink-1"],
        "statusBar.debuggingBackground": tok["aka-2"], "statusBar.debuggingForeground": "#F7EED2",
        "statusBarItem.remoteBackground": tok["ink-2"], "statusBarItem.remoteForeground": gold_t,
        "statusBarItem.hoverBackground": aa(tok["bone-0"], "10"),
        "statusBarItem.errorBackground": tok["ink-1"], "statusBarItem.errorForeground": tok["aka-0"],
        "activityBar.background": tok["ink-1"], "activityBar.foreground": gold_t,
        "activityBar.inactiveForeground": tok["bone-4"], "activityBar.border": tok["line-0"],
        "activityBar.activeBorder": gold_e,
        "activityBarBadge.background": tok["ink-3"], "activityBarBadge.foreground": gold_t,
        "sideBar.background": tok["ink-1"], "sideBar.foreground": tok["bone-2"],
        "sideBar.border": tok["line-0"], "sideBarTitle.foreground": tok["bone-3"],
        "sideBarSectionHeader.background": tok["ink-1"], "sideBarSectionHeader.foreground": tok["bone-3"],
        "sideBarSectionHeader.border": tok["line-0"],
        # lists / trees
        "list.activeSelectionBackground": tok["ink-3"], "list.activeSelectionForeground": tok["bone-0"],
        "list.activeSelectionIconForeground": gold_t,
        "list.inactiveSelectionBackground": tok["ink-2"], "list.inactiveSelectionForeground": tok["bone-1"],
        "list.hoverBackground": aa(tok["bone-0"], "0a"), "list.focusBackground": tok["ink-3"],
        "list.highlightForeground": gold_t, "list.errorForeground": tok["aka-0"],
        "list.warningForeground": tok["kaki-1"], "tree.indentGuidesStroke": tok["line-0"],
        # inputs / dropdowns / buttons / badges
        "input.background": tok["ink-1"] if not light else tok["ink-2"], "input.foreground": tok["bone-1"],
        "input.border": tok["line-1"], "input.placeholderForeground": tok["bone-4"],
        "inputOption.activeBorder": gold_e, "inputOption.activeForeground": gold_t,
        "inputOption.activeBackground": aa(gold_e, "22"),
        "inputValidation.errorBackground": tok["aka-w"], "inputValidation.errorBorder": tok["aka-1"],
        "dropdown.background": tok["ink-1"], "dropdown.foreground": tok["bone-1"], "dropdown.border": tok["line-1"],
        "button.background": tok["ink-2"], "button.foreground": gold_t, "button.border": gold_e,
        "button.hoverBackground": tok["ink-3"],
        "button.secondaryBackground": tok["ink-2"], "button.secondaryForeground": tok["bone-2"],
        "badge.background": tok["ink-3"], "badge.foreground": gold_t,
        "checkbox.background": tok["ink-2"], "checkbox.border": tok["line-1"], "checkbox.foreground": gold_t,
        # menus / keybinding labels / breadcrumb
        "menu.background": tok["ink-1"], "menu.foreground": tok["bone-2"],
        "menu.selectionBackground": tok["ink-3"], "menu.selectionForeground": tok["bone-0"],
        "menu.border": tok["line-0"], "menu.separatorBackground": tok["line-0"],
        "keybindingLabel.background": tok["ink-2"], "keybindingLabel.foreground": tok["bone-2"],
        "keybindingLabel.border": tok["line-0"], "keybindingLabel.bottomBorder": tok["line-1"],
        "breadcrumb.foreground": tok["bone-3"], "breadcrumb.focusForeground": tok["bone-1"],
        "breadcrumb.activeSelectionForeground": gold_t, "breadcrumb.background": ebg,
        # panel + integrated terminal (dark island for both themes)
        "panel.background": tok["ink-1"], "panel.border": tok["line-0"],
        "panelTitle.activeForeground": tok["bone-0"], "panelTitle.inactiveForeground": tok["bone-4"],
        "panelTitle.activeBorder": gold_e,
        "terminal.background": term["background"], "terminal.foreground": term["foreground"],
        "terminalCursor.foreground": term["cursor"], "terminalCursor.background": term["background"],
        "terminal.selectionBackground": aa("#" + term["selection_background"].lstrip("#"), "99"),
        "terminal.border": tok["line-0"],
        # git decorations
        "gitDecoration.modifiedResourceForeground": tok["kaki-1"],
        "gitDecoration.deletedResourceForeground": tok["aka-0"],
        "gitDecoration.untrackedResourceForeground": tok["mori-0"],
        "gitDecoration.addedResourceForeground": tok["mori-0"],
        "gitDecoration.ignoredResourceForeground": tok["bone-4"],
        "gitDecoration.conflictingResourceForeground": tok["fuji-1"],
        "gitDecoration.stageModifiedResourceForeground": gold_t,
        "gitDecoration.stageDeletedResourceForeground": tok["aka-2"],
        # notifications / minimap / links / charts
        "notifications.background": tok["ink-1"], "notifications.border": tok["line-0"],
        "notificationCenterHeader.background": tok["ink-2"],
        "notificationsErrorIcon.foreground": tok["aka-0"],
        "notificationsWarningIcon.foreground": tok["kaki-1"],
        "notificationsInfoIcon.foreground": gold_t,
        "minimap.findMatchHighlight": aa(gold_hi, "99"), "minimap.selectionHighlight": aa(gold_e, "55"),
        "minimap.errorHighlight": tok["aka-1"],
        "textLink.foreground": gold_t, "textLink.activeForeground": gold_hi,
        "textCodeBlock.background": tok["ink-1"], "textPreformat.foreground": tok["kaki-1"],
        "charts.foreground": tok["bone-2"], "charts.lines": tok["line-1"],
        "charts.red": tok["aka-0"], "charts.blue": tok["hotaru-1"], "charts.yellow": tok["kin-1"],
        "charts.green": tok["mori-0"], "charts.orange": tok["kaki-1"], "charts.purple": tok["fuji-1"],
    }
    colors.update(ansi_colors)

    vscode = {
        "$schema": "vscode://schemas/color-theme",
        "name": f"yoshiki {slug}", "type": p["meta"]["mode"],
        "semanticHighlighting": True,
        "colors": colors,
        "tokenColors": [
            tc(["comment", "punctuation.definition.comment"], sx("syntax.comment"), "italic"),
            tc(["keyword", "storage", "storage.type", "storage.modifier",
                "keyword.control", "keyword.operator.new", "keyword.operator.expression"], sx("syntax.keyword")),
            tc(["keyword.operator"], tok["bone-2"]),
            tc(["entity.name.tag", "entity.name.tag.html"], sx("syntax.keyword")),
            tc(["string", "string.quoted", "string.template"], sx("syntax.string")),
            tc(["constant.character.escape", "punctuation.definition.template-expression"], gold_t),
            tc(["constant.numeric", "constant.numeric.integer", "constant.numeric.float"], sx("syntax.number")),
            tc(["constant.language", "constant.language.boolean", "variable.language"], sx("syntax.constant")),
            tc(["constant.other", "support.constant"], tok["kaki-1"]),
            tc(["entity.name.function", "support.function", "meta.function-call.generic"], tok["bone-0"]),
            tc(["entity.name.type", "support.type", "entity.name.class",
                "support.class", "entity.other.inherited-class"], sx("syntax.type")),
            tc(["variable", "meta.definition.variable.name", "support.variable"], tok["bone-1"]),
            tc(["variable.parameter", "meta.parameter"], tok["bone-2"]),
            tc(["variable.other.property", "support.variable.property", "meta.object-literal.key"], tok["bone-2"]),
            tc(["support.type.property-name.json", "support.type.property-name"], gold_t),
            tc(["entity.other.attribute-name"], tok["kaki-1"]),
            tc(["punctuation", "meta.brace", "punctuation.separator", "punctuation.terminator"], tok["bone-3"]),
            tc(["markup.heading", "markup.heading entity.name", "entity.name.section"], gold_t, "bold"),
            tc(["markup.bold"], tok["bone-0"], "bold"),
            tc(["markup.italic"], tok["bone-1"], "italic"),
            tc(["markup.inline.raw", "markup.fenced_code", "markup.raw"], tok["mori-0"]),
            tc(["markup.quote"], tok["bone-3"], "italic"),
            tc(["markup.underline.link", "string.other.link", "constant.other.reference.link"], gold_t, "underline"),
            tc(["markup.inserted", "punctuation.definition.inserted"], tok["mori-0"]),
            tc(["markup.deleted", "punctuation.definition.deleted"], tok["aka-0"]),
            tc(["markup.changed", "punctuation.definition.changed"], tok["kaki-1"]),
            tc(["meta.diff.header", "punctuation.definition.from-file", "punctuation.definition.to-file"], tok["fuji-1"]),
            tc(["invalid", "invalid.illegal", "message.error"], tok["aka-0"]),
            tc(["token.info-token"], gold_t), tc(["token.warn-token"], tok["kaki-1"]),
            tc(["token.error-token"], tok["aka-0"]), tc(["token.debug-token"], tok["fuji-1"]),
        ],
        "semanticTokenColors": {
            "parameter": tok["bone-2"], "property": tok["bone-2"], "variable": tok["bone-1"],
            "variable.readonly": tok["fuji-1"], "function": tok["bone-0"], "method": tok["bone-0"],
            "class": tok["hotaru-1"], "type": tok["hotaru-1"], "enum": tok["hotaru-1"],
            "interface": tok["hotaru-1"], "struct": tok["hotaru-1"], "typeParameter": tok["hotaru-1"],
            "namespace": tok["bone-2"], "keyword": sx("syntax.keyword"),
            "string": sx("syntax.string"), "number": sx("syntax.number"),
            "enumMember": tok["kaki-1"], "macro": tok["fuji-1"], "decorator": tok["kaki-1"],
            "comment": {"foreground": sx("syntax.comment"), "fontStyle": "italic"},
            "*.deprecated": {"fontStyle": "strikethrough"},
        },
    }
    w(LIB / "vscode" / f"{slug}.json", json.dumps(vscode, ensure_ascii=False, indent=2) + "\n")

    # neovim — lua colorscheme (core + treesitter)
    nv = [f"-- {head}", '-- usage: copy to colors/, then :colorscheme yoshiki-' + slug,
          'vim.cmd("highlight clear")', 'vim.cmd("syntax reset")',
          f'vim.o.background = "{p["meta"]["mode"]}"',
          f'vim.g.colors_name = "yoshiki-{slug}"',
          "local hl = vim.api.nvim_set_hl"]
    hi = [("Normal", efg, ebg), ("Comment", tok["bone-4"], None),
          ("Keyword", tok["kin-1"], None), ("Statement", tok["kin-1"], None),
          ("String", tok["mori-0"], None), ("Number", tok["kaki-1"], None),
          ("Function", tok["bone-0"], None), ("Type", tok["hotaru-1"], None),
          ("Constant", tok["fuji-1"], None), ("Identifier", tok["bone-1"], None),
          ("Error", tok["aka-0"], None), ("LineNr", tok["bone-4"], None),
          ("CursorLineNr", tok["kin-1"], None), ("Visual", None, sel),
          ("Pmenu", tok["bone-2"], tok["ink-2"]), ("PmenuSel", tok["ink-0"], tok["kin-1"])]
    for g, f_, b_ in hi:
        parts = []
        if f_:
            parts.append(f'fg = "{f_}"')
        if b_:
            parts.append(f'bg = "{b_}"')
        if g == "Comment":
            parts.append("italic = true")
        nv.append(f'hl(0, "{g}", {{ {", ".join(parts)} }})')
    nv += [f'hl(0, "@{a}", {{ link = "{b}" }})' for a, b in
           [("keyword", "Keyword"), ("string", "String"), ("number", "Number"),
            ("function", "Function"), ("type", "Type"), ("comment", "Comment"),
            ("constant", "Constant")]]
    w(LIB / "neovim" / f"{slug}.lua", "\n".join(nv) + "\n")

    # tmux — status palette (generated; mirrors the hand config in ../configs/tmux)
    tm = [f"# {head}",
          f'set -g status-style "bg={ebg},fg={tok["bone-3"]}"',
          f'set -g status-left-style "fg={tok["kin-1"]}"',
          f'set -g window-status-current-style "fg={tok["bone-0"]}"',
          f'set -g window-status-style "fg={tok["bone-4"]}"',
          f'set -g status-right-style "fg={tok["kin-2"]}"',
          f'set -g pane-border-style "fg={tok["line-0"]}"',
          f'set -g pane-active-border-style "fg={tok["kin-2"]}"',
          f'set -g mode-style "bg={sel},fg={tok["bone-0"]}"']
    w(LIB / "tmux" / f"{slug}.tmux", "\n".join(tm) + "\n")

    # btop — theme
    def bt(k, c):
        return f'theme[{k}]="{c}"'
    a, br = term["ansi"], term["brights"]
    bp = [f"# {head}",
          bt("main_bg", ebg), bt("main_fg", efg),
          bt("title", tok["bone-0"]), bt("hi_fg", tok["kin-1"]),
          bt("selected_bg", sel), bt("selected_fg", tok["kin-0"]),
          bt("inactive_fg", tok["bone-4"]), bt("graph_text", tok["bone-2"]),
          bt("proc_misc", tok["mori-0"]), bt("cpu_box", tok["line-1"]),
          bt("div_line", tok["line-0"]),
          bt("temp_start", tok["mori-1"]), bt("temp_mid", tok["kaki-1"]), bt("temp_end", tok["aka-1"]),
          bt("cpu_start", tok["mori-1"]), bt("cpu_mid", tok["kin-2"]), bt("cpu_end", tok["kin-0"]),
          bt("free_start", tok["seiji-1"]), bt("free_mid", tok["hotaru-1"]), bt("free_end", tok["fuji-1"])]
    w(LIB / "btop" / f"{slug}.theme", "\n".join(bp) + "\n")


# text roles measured against their real background, with the WCAG floor
CONTRAST_ROWS = [
    ("text.heading", "bg.surface", 4.5), ("text.body", "bg.surface", 4.5),
    ("text.secondary", "bg.surface", 4.5), ("text.muted", "bg.surface", 4.5),
    ("text.ghost", "bg.surface", 3.0), ("text.gold", "bg.surface", 4.5),
    ("action.text", "bg.raised", 4.5), ("ok.text", "ok.wash", 4.5),
    ("warn.text", "bg.surface", 3.0), ("danger.text", "danger.wash", 4.5),
    ("special.text", "bg.surface", 4.5),
]


def write_contrast(resolved: dict):
    head = ["# Contrast — WCAG proof\n",
            "Auto-generated by `tools/build.py`. Every text role is measured against",
            "the background it actually sits on. Decorative gold edges (`border.gold`)",
            "are excluded — an edge needs only 3:1, and gold-as-text uses `text.gold`.\n"]
    lines = []
    ok_all = True
    for p in resolved.values():
        tok = p["tokens"]

        def hexof(role):
            return role_value(p["roles"][role], tok)[1]
        lines.append(f"## {p['meta']['name']} ({p['meta']['mode']})\n")
        lines.append("| role | on | ratio | floor | |")
        lines.append("|---|---|---|---|---|")
        for fg, bg, floor in CONTRAST_ROWS:
            c = contrast(hexof(fg), hexof(bg))
            ok = c >= floor
            ok_all &= ok
            lines.append(f"| `{fg}` | `{bg}` | {c}:1 | {floor} | {'✓' if ok else '✗ FAIL'} |")
        lines.append("")
    head.append(f"**Status: {'all roles pass' if ok_all else 'FAILURES PRESENT'}.**\n")
    w(PAL / "CONTRAST.md", "\n".join(head + lines))
    return ok_all


def main():
    resolved = {}
    for slug in ORDER:
        raw = load(slug)
        parent = resolved.get(raw.get("inherits", ""))
        resolved[slug] = resolve(raw, parent)
        emit(slug, resolved[slug])
    ok = write_contrast(resolved)
    print("done." if ok else "done — CONTRAST FAILURES, see CONTRAST.md")


if __name__ == "__main__":
    main()
