"""Read the workshop extraction files into one catalogue.

`workshop/refs/extract/parts-*.md` hold blocks in the format of workshop/EXTRACTION.md:

    - ref: yk:ref/0042
      kind: object
      name: segmented-toggle-pill
      what: …
      build: … (may wrap over several indented lines)
      zone: graphic
      use: …
      style: soft product UI
      notable: true

The files are written by hand-ish (agents), so parsing is forgiving: a block starts at a
line beginning `- ref:`, keys are `key: value`, and any indented line that is not a new key
continues the previous value. Everything else in the file (prose, headings, the closing
register list) is ignored.

    python3 tools/parts.py            # write workshop/refs/extract/catalogue.json + a summary
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXTRACT = ROOT / "workshop" / "refs" / "extract"
KEY = re.compile(r"^\s{2,}([a-z][a-z-]*):\s*(.*)$")
START = re.compile(r"^\s*-\s+ref:\s*(\S+)")


# Registers as the agents wrote them are free text; these rules fold them into the few
# stylistic worlds the library actually holds. First match wins, so the specific rules
# (palette card, NieR menu) come before the broad ones (soft product UI).
REGISTERS = [
    ("palette-card", ["palette card", "palette template", "palette-card", "palette device", "botanical dark luxury palette", "brand palette"]),
    ("nier-menu", ["nier"]),
    ("japanese-paper", ["washi", "japanese", "literary vertical", "lacquer", "sepia calligraph", "anime", "ink poster"]),
    ("soft-relief", ["relief", "neumorph", "skeuomorph"]),
    ("print-halftone", ["halftone", "op-art", "cross-stitch", "risograph", "print"]),
    ("moodboard-collage", ["moodboard", "collage", "pulp poster", "romantic dark editorial", "editorial studio"]),
    ("generative-3d", ["particle", "3d render", "extrusion", "x-ray", "wireframe generative", "generative diagram"]),
    ("blueprint-hud", ["hud", "blueprint", "dot-matrix", "data-map", "military tech", "industrial rave", "crypto grid", "dark tech", "technical"]),
    ("glass-product", ["glass"]),
    ("brutalist-mono", ["brutalist", "grunge", "glitch", "mono /", "generative mono"]),
    ("swiss-editorial", ["swiss", "editorial", "luxury print", "logotype", "typograph", "construction poster"]),
    ("lo-fi-warm", ["lo-fi", "warm", "lounge", "photograph", "hospitality"]),
    ("soft-product", ["product ui", "saas", "dashboard", "fintech", "app", "e-commerce", "wellness", "creative tool",
                       "auth product", "folder icons", "layout pack", "tool", "product"]),
]


def register(style: str) -> str:
    s = (style or "").lower()
    for name, keys in REGISTERS:
        if any(k in s for k in keys):
            return name
    return "other"


def parse(text: str, source: str) -> list[dict]:
    items, cur, last = [], None, None
    for raw in text.splitlines():
        m = START.match(raw)
        if m:
            if cur:
                items.append(cur)
            cur = {"ref": m.group(1).strip(), "source": source}
            last = "ref"
            continue
        if cur is None:
            continue
        k = KEY.match(raw)
        if k:
            key, val = k.group(1), k.group(2).strip()
            cur[key] = val
            last = key
        elif raw.strip() and raw.startswith(" ") and last:
            cur[last] = (cur[last] + " " + raw.strip()).strip()
        elif not raw.strip():
            continue
        else:                      # a non-indented line ends the block
            items.append(cur)
            cur, last = None, None
    if cur:
        items.append(cur)
    return [i for i in items if i.get("kind") and (i.get("name") or i.get("what"))]


def load() -> list[dict]:
    out: list[dict] = []
    for f in sorted(EXTRACT.glob("parts-*.md")):
        out += parse(f.read_text(), f.name)
    return out


def summarise(items: list[dict]) -> dict:
    kinds: dict = {}
    styles: dict = {}
    groups: dict = {}
    refs = set()
    for i in items:
        kinds[i.get("kind", "?")] = kinds.get(i.get("kind", "?"), 0) + 1
        s = (i.get("style") or "").strip().lower()
        if s:
            styles[s] = styles.get(s, 0) + 1
        g = i.setdefault("register", register(s))
        groups[g] = groups.get(g, 0) + 1
        refs.add(i.get("ref"))
    return {"components": len(items), "references": len(refs),
            "kinds": dict(sorted(kinds.items(), key=lambda x: -x[1])),
            "registers": dict(sorted(groups.items(), key=lambda x: -x[1])),
            "styles": dict(sorted(styles.items(), key=lambda x: -x[1]))}


def main():
    items = load()
    if not items:
        sys.exit("no extraction files yet — workshop/refs/extract/parts-*.md")
    data = {"$comment": "yoshiki workshop catalogue — generated by tools/parts.py from the extraction files.",
            "summary": summarise(items), "items": items}
    (EXTRACT / "catalogue.json").write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n")
    s = data["summary"]
    print(f"{s['components']} components from {s['references']} references")
    print("kinds:", ", ".join(f"{k} {v}" for k, v in s["kinds"].items()))
    print("registers:", ", ".join(f"{k} {v}" for k, v in s["registers"].items()))


if __name__ == "__main__":
    main()
